### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oertels** [acdha/django-speedtracer#1]
Hi there,

I like the idea of your app and installed following your README: Downloaded a Chrome Dev (currently something like 9.0.x dev), then SpeedTracer. I start Chrome on a Mac with the "ChromeWithSpeedTracer.app", and the SpeedTracer-Extensions works, but I don't see a "Server Trace" Tab in it. I can see that I installed your app properly by setting "SPEEDTRACEr_DEBUG" in the projeject settings: there is a lot of debug output, but it simply does not arrive in Chrome. Any idea about this?

**Comment by acdha** [comment]
As far as I can tell, it looks like something might have changed or recently broken in Chrome Dev channel. Looking at a response, I see the expected header (e.g. `X-TraceUrl: /__speedtracer__/749dc392-cab5-40d0-9be4-6eab4e493430`) and fetching that URL returns what appears to be correct JSON.

Any chance you could try this with the current chrome release? I wonder if the expected response format has changed recently.

**Comment by cce** [comment]
I had a similar problem -- but then I fixed it by removing an old Chromium.app snapshot from my /Applications/ directory.  running "strings /Applications/ChromeWithSpeedTracer.app/Contents/MacOS/ChromeWithSpeedTracer" revealed that ChromeWithSpeedTracer.app was searching for strings like "Chromium.app", "Google Chrome.app" and "Chrome.app", finding the Chromium build before my Google Chrome dev channel .app version and invoking Chromium, instead.  If you have multiple copies of Chrome/Chromium in your Applications folder this may be the problem.

You could also diagnose this with "ps auxww | grep Chrom" to see what binary is being invoked by the ChromeWithSpeedTracer launcher.

**Comment by acdha** [comment]
schneck: is this still a problem for you? I've verified that Google's SpeedTracer extension (0.21) is currently broken with Chrome Dev channel but fully functional using the stable version. An easy way to verify this is to look for headers in the network view: if the request/response headers are empty, you're being affected by this bug.

I believe this is the corresponding upstream issue:
http://code.google.com/p/speedtracer/issues/detail?id=28

**Comment by acdha** [comment]
Closing - it's working for me with current Chrome; reopen if you still have a problem on an otherwise functional SpeedTracer.
